    <option selected="">--Tỉnh/TP bạn đang làm việc--</option>
    <option data-id="01" value="Hà Nội">Hà Nội</option>
    <option data-id="79" value="TP. Hồ Chí Minh">TP. Hồ Chí Minh</option>
    <option data-id="02" value="Hà Giang">Hà Giang</option>
    <option data-id="04" value="Cao Bằng">Cao Bằng</option>
    <option data-id="06" value="Bắc Kạn">Bắc Kạn</option>
    <option data-id="08" value="Tuyên Quang">Tuyên Quang</option>
    <option data-id="10" value="Lào Cai">Lào Cai</option>
    <option data-id="11" value="Điện Biên">Điện Biên</option>
    <option data-id="12" value="Lai Châu">Lai Châu</option>
    <option data-id="14" value="Sơn La">Sơn La</option>
    <option data-id="15" value="Yên Bái">Yên Bái</option>
    <option data-id="17" value="Hòa Bình">Hòa Bình</option>
    <option data-id="19" value="Thái Nguyên">Thái Nguyên</option>
    <option data-id="20" value="Lạng Sơn">Lạng Sơn</option>
    <option data-id="22" value="Quảng Ninh">Quảng Ninh</option>
    <option data-id="24" value="Bắc Giang">Bắc Giang</option>
    <option data-id="25" value="Phú Thọ">Phú Thọ</option>
    <option data-id="26" value="Vĩnh Phúc">Vĩnh Phúc</option>
    <option data-id="27" value="Bắc Ninh">Bắc Ninh</option>
    <option data-id="30" value="Hải Dương">Hải Dương</option>
    <option data-id="31" value="Hải Phòng">Hải Phòng</option>
    <option data-id="33" value="Hưng Yên">Hưng Yên</option>
    <option data-id="34" value="Thái Bình">Thái Bình</option>
    <option data-id="35" value="Hà Nam">Hà Nam</option>
    <option data-id="36" value="Nam Định">Nam Định</option>
    <option data-id="37" value="Ninh Bình">Ninh Bình</option>
    <option data-id="38" value="Thanh Hóa">Thanh Hóa</option>
    <option data-id="40" value="Nghệ An">Nghệ An</option>
    <option data-id="42" value="Hà Tĩnh">Hà Tĩnh</option>
    <option data-id="44" value="Quảng Bình">Quảng Bình</option>
    <option data-id="45" value="Quảng Trị">Quảng Trị</option>
    <option data-id="46" value="Thừa Thiên Huế">Thừa Thiên Huế</option>
    <option data-id="48" value="Đà Nẵng">Đà Nẵng</option>
    <option data-id="49" value="Quảng Nam">Quảng Nam</option>
    <option data-id="51" value="Quảng Ngãi">Quảng Ngãi</option>
    <option data-id="52" value="Bình Định">Bình Định</option>
    <option data-id="54" value="Phú Yên">Phú Yên</option>
    <option data-id="56" value="Khánh Hòa">Khánh Hòa</option>
    <option data-id="58" value="Ninh Thuận">Ninh Thuận</option>
    <option data-id="60" value="Bình Thuận">Bình Thuận</option>
    <option data-id="62" value="Kon Tum">Kon Tum</option>
    <option data-id="64" value="Gia Lai">Gia Lai</option>
    <option data-id="66" value="Đắk Lắk">Đắk Lắk</option>
    <option data-id="67" value="Đắk Nông">Đắk Nông</option>
    <option data-id="68" value="Lâm Đồng">Lâm Đồng</option>
    <option data-id="70" value="Bình Phước">Bình Phước</option>
    <option data-id="72" value="Tây Ninh">Tây Ninh</option>
    <option data-id="74" value="Bình Dương">Bình Dương</option>
    <option data-id="75" value="Đồng Nai">Đồng Nai</option>
    <option data-id="77" value="Bà Rịa - Vũng Tàu">Bà Rịa - Vũng Tàu</option>
    <option data-id="80" value="Long An">Long An</option>
    <option data-id="82" value="Tiền Giang">Tiền Giang</option>
    <option data-id="83" value="Bến Tre">Bến Tre</option>
    <option data-id="84" value="Trà Vinh">Trà Vinh</option>
    <option data-id="86" value="Vĩnh Long">Vĩnh Long</option>
    <option data-id="87" value="Đồng Tháp">Đồng Tháp</option>
    <option data-id="89" value="An Giang">An Giang</option>
    <option data-id="91" value="Kiên Giang">Kiên Giang</option>
    <option data-id="92" value="Cần Thơ">Cần Thơ</option>
    <option data-id="93" value="Hậu Giang">Hậu Giang</option>
    <option data-id="94" value="Sóc Trăng">Sóc Trăng</option>
    <option data-id="95" value="Bạc Liêu">Bạc Liêu</option>
    <option data-id="96" value="Cà Mau">Cà Mau</option>